version: '3.8'

services:
  web:
    build: .
    container_name: digest-generator
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow 